#!/usr/bin/env bash

echo "正在编译项目...."

mvn package  org.apache.maven.plugins:maven-jar-plugin:2.6:jar org.springframework.boot:spring-boot-maven-plugin:1.3.6.RELEASE:repackage -Dmaven.test.skip=true

if [ "X$?" != "X0" ]; then
        echo "编译失败！"
        exit 1
fi

echo "编译完成...."


IMAGE_NAME=${IMAGE_NAME:-"c-dev.sondon.net/service/report:latest"}

docker build -t $IMAGE_NAME .

echo "当前打包镜像为：$IMAGE_NAME"

docker push $IMAGE_NAME

echo "推送到镜像仓库"